/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tom.ui;

import com.tom.AppSharedData.AppSharedData;
import com.tom.mongoDB.MongoServerInstance;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.io.PrintStream;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author csaini
 */
public class MainFrame extends javax.swing.JFrame {

    ExecuteCommands executeCommands;
    List<JPanel> charts;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        JTextAreaOutputStream out = new JTextAreaOutputStream(jTextArea1);
        System.setOut(new PrintStream(out));
        executeCommands = new ExecuteCommands();
        executeCommands.uploadFont();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane_charts = new javax.swing.JScrollPane();
        jPanel_charts = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton_ImportFromExcel = new javax.swing.JButton();
        jButton_SaveChartImages = new javax.swing.JButton();
        jButton_CreateCharts = new javax.swing.JButton();
        jButton_ViewRecords = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Text Output / Console"));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Clear Messages");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1026;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 12, 0, 12);
        getContentPane().add(jPanel1, gridBagConstraints);

        jScrollPane_charts.setViewportBorder(javax.swing.BorderFactory.createTitledBorder("Output Area"));

        jPanel_charts.setFocusable(false);

        javax.swing.GroupLayout jPanel_chartsLayout = new javax.swing.GroupLayout(jPanel_charts);
        jPanel_charts.setLayout(jPanel_chartsLayout);
        jPanel_chartsLayout.setHorizontalGroup(
            jPanel_chartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1264, Short.MAX_VALUE)
        );
        jPanel_chartsLayout.setVerticalGroup(
            jPanel_chartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jScrollPane_charts.setViewportView(jPanel_charts);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 960;
        gridBagConstraints.ipady = 475;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(13, 12, 0, 12);
        getContentPane().add(jScrollPane_charts, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Quick Options"));
        jPanel2.setToolTipText("");

        jButton_ImportFromExcel.setText("Import From Excel");
        jButton_ImportFromExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ImportFromExcelActionPerformed(evt);
            }
        });

        jButton_SaveChartImages.setText("Save Chart Images");
        jButton_SaveChartImages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SaveChartImagesActionPerformed(evt);
            }
        });

        jButton_CreateCharts.setText("Create Charts");
        jButton_CreateCharts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CreateChartsActionPerformed(evt);
            }
        });

        jButton_ViewRecords.setText("View Records");
        jButton_ViewRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ViewRecordsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton_ImportFromExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_CreateCharts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_ViewRecords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_SaveChartImages, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton_ImportFromExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_ViewRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_CreateCharts, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_SaveChartImages, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 324;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 0, 0, 0);
        getContentPane().add(jPanel2, gridBagConstraints);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("MongoDB");

        jMenuItem1.setText("Check Server Connection");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ImportFromExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ImportFromExcelActionPerformed
        FileInput fileInput = new FileInput(executeCommands);
        fileInput.setVisible(true);//show user the file input window
    }//GEN-LAST:event_jButton_ImportFromExcelActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        executeCommands.checkMongoDB();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton_ViewRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ViewRecordsActionPerformed
        if (!AppSharedData.MongoRunning) {
            MongoServerInstance.getInstance();
        }
        jPanel_charts.removeAll();
        jPanel_charts.invalidate();
         
        jPanel_charts.setLayout(new BorderLayout());
        JTable table = executeCommands.showDataTable();
        System.out.println("size " + jPanel_charts.getSize());
        table.setSize(jPanel_charts.getSize());
        jPanel_charts.add(table, BorderLayout.CENTER);
        jPanel_charts.add(table.getTableHeader(), BorderLayout.NORTH);//column titles
        jPanel_charts.revalidate();
        jPanel_charts.repaint();

    }//GEN-LAST:event_jButton_ViewRecordsActionPerformed

    private void jButton_CreateChartsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CreateChartsActionPerformed
        jPanel_charts.removeAll();//remove all the stuff from the panel
        jPanel_charts.invalidate();
        jPanel_charts.setSize(957, 460);
//        jPanel_charts.setLayout(new FlowLayout());
        jPanel_charts.setLayout(new GridLayout(0, 1, 5, 5));
        jPanel_charts.setMaximumSize(new Dimension(957, 460));
        Dimension d = new Dimension(560, 450);//chart size
        charts = executeCommands.createCharts(d);
        System.out.println("Total Charts " + charts.size());
        for (JPanel chart : charts) {
            jPanel_charts.add(chart);
        }
        jPanel_charts.revalidate();
        jPanel_charts.repaint();
    }//GEN-LAST:event_jButton_CreateChartsActionPerformed

    private void jButton_SaveChartImagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SaveChartImagesActionPerformed
        try {
            Path dirPath = Paths.get("C:\\Tom Chart Images");
            if (!Files.exists(dirPath, LinkOption.NOFOLLOW_LINKS)) {
                Files.createDirectories(dirPath);
            }
            System.out.println("Total Charts saved : " + charts.size());
            for (int i = 0; i < charts.size(); i++) {
                File file = new File("C:\\Tom Chart Images\\" + i + ".jpg");
                BufferedImage bi= ScreenImage.createImage(charts.get(i));               
                ImageIO.write( bi, "JPEG", file);
            }
            System.out.println("Files Saved in " + dirPath);
        } catch (IOException e) {
            System.out.println(e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton_SaveChartImagesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_CreateCharts;
    private javax.swing.JButton jButton_ImportFromExcel;
    private javax.swing.JButton jButton_SaveChartImages;
    private javax.swing.JButton jButton_ViewRecords;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_charts;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane_charts;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
